Revert "gh-274: Handle blocking I/O errors in GreenSocket"
The commit broke tests on Python 3[1]:

======================================================================
FAIL: test_recv_into_timeout (tests.greenio_test.TestGreenSocket)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/eventlet/eventlet/tests/greenio_test.py", line 192, in test_recv_into_timeout
    self.fail("socket.timeout not raised")
AssertionError: socket.timeout not raised

This reverts commit 19035b10185e10719a2d34bf911d52967a8c6d08.

[1] https://travis-ci.org/eventlet/eventlet/jobs/100720347